use anchor_lang::prelude::*;
use anchor_lang::system_program;
use anchor_spl::token_interface::{Mint, TokenAccount, TokenInterface};

use crate::constants::*;
use crate::errors::TmbError;
use crate::events::BroMinted;
use crate::logic::{bps_of, tmb_payout_allowed};
use crate::state::*;
use crate::utils::core_mint;

pub fn handler(ctx: Context<MintBro>, name: String, uri: String) -> Result<()> {
    require!(
        name.len() <= MAX_NAME_LEN && uri.len() <= MAX_URI_LEN,
        TmbError::StringTooLong
    );
    let c = &mut ctx.accounts.config;
    require!(!c.paused, TmbError::Paused);
    require!(
        c.collection != Pubkey::default(),
        TmbError::CollectionNotSet
    );
    require!(c.minted < c.max_supply, TmbError::MaxSupply);

    // --- payment split: pool share -> treasury, remainder -> team wallet ---
    let price = c.mint_price_lamports;
    let to_treasury = bps_of(price, c.mint_pool_share_bps).ok_or(TmbError::Overflow)?;
    let to_team = price.checked_sub(to_treasury).ok_or(TmbError::Overflow)?;
    if to_treasury > 0 {
        system_program::transfer(
            CpiContext::new(
                ctx.accounts.system_program.to_account_info(),
                system_program::Transfer {
                    from: ctx.accounts.player.to_account_info(),
                    to: ctx.accounts.treasury.to_account_info(),
                },
            ),
            to_treasury,
        )?;
    }
    if to_team > 0 {
        system_program::transfer(
            CpiContext::new(
                ctx.accounts.system_program.to_account_info(),
                system_program::Transfer {
                    from: ctx.accounts.player.to_account_info(),
                    to: ctx.accounts.team_wallet.to_account_info(),
                },
            ),
            to_team,
        )?;
    }

    // --- starting balance (credited from the pool only if the payout guard allows) ---
    let pool = c.pool(ctx.accounts.vault_tmb.amount);
    let start = if c.mint_starting_balance > 0
        && tmb_payout_allowed(
            pool,
            c.mint_starting_balance,
            c.max_payout_bps,
            c.min_reserve,
        ) {
        c.mint_starting_balance
    } else {
        0
    };
    c.total_user_tmb = c
        .total_user_tmb
        .checked_add(start)
        .ok_or(TmbError::Overflow)?;
    c.minted = c.minted.checked_add(1).ok_or(TmbError::Overflow)?;

    let b = &mut ctx.accounts.bro_record;
    b.asset = ctx.accounts.asset.key();
    b.owner = ctx.accounts.player.key();
    b.loss_streak = 0;
    b.tmb_balance = start;
    b.holdings = Vec::new();
    b.status = BroStatus::Active;
    b.in_escrow = false;
    b.pending_spin = None;
    b.total_spins = 0;
    b.eligible_slot = 0;
    b.bump = ctx.bumps.bro_record;

    let cfg_bump = c.bump;
    core_mint(
        &ctx.accounts.mpl_core_program.to_account_info(),
        &ctx.accounts.asset.to_account_info(),
        &ctx.accounts.collection.to_account_info(),
        &ctx.accounts.config.to_account_info(),
        cfg_bump,
        &ctx.accounts.player.to_account_info(),
        &ctx.accounts.player.to_account_info(),
        &ctx.accounts.system_program.to_account_info(),
        name,
        uri,
    )?;
    emit!(BroMinted {
        asset: ctx.accounts.asset.key(),
        owner: ctx.accounts.player.key(),
        price_lamports: price,
        starting_balance: start,
        bonus: false,
    });
    Ok(())
}

#[derive(Accounts)]
pub struct MintBro<'info> {
    #[account(mut)]
    pub player: Signer<'info>,
    #[account(mut, seeds = [CONFIG_SEED], bump = config.bump)]
    pub config: Box<Account<'info, Config>>,
    /// New Core asset keypair, generated by the client.
    #[account(mut)]
    pub asset: Signer<'info>,
    /// CHECK: must be the configured Bro collection.
    #[account(mut, address = config.collection @ TmbError::CollectionNotSet)]
    pub collection: UncheckedAccount<'info>,
    /// CHECK: configured SOL treasury.
    #[account(mut, address = config.treasury)]
    pub treasury: UncheckedAccount<'info>,
    /// CHECK: configured team wallet (remainder of the mint price).
    #[account(mut, address = config.team_wallet)]
    pub team_wallet: UncheckedAccount<'info>,
    #[account(
        init, payer = player, space = 8 + BroRecord::INIT_SPACE,
        seeds = [BRO_SEED, asset.key().as_ref(), player.key().as_ref()], bump
    )]
    pub bro_record: Box<Account<'info, BroRecord>>,
    /// CHECK: PDA owning the vault token accounts.
    #[account(seeds = [VAULT_SEED], bump = config.vault_bump)]
    pub vault: UncheckedAccount<'info>,
    #[account(address = config.tmb_mint)]
    pub tmb_mint: InterfaceAccount<'info, Mint>,
    #[account(
        associated_token::mint = tmb_mint,
        associated_token::authority = vault,
        associated_token::token_program = token_program
    )]
    pub vault_tmb: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
    /// CHECK: pinned to the Metaplex Core program.
    #[account(address = mpl_core::ID)]
    pub mpl_core_program: UncheckedAccount<'info>,
    pub system_program: Program<'info, System>,
}
