use anchor_lang::prelude::*;
use anchor_spl::token_interface::{self, Burn, Mint, TokenAccount, TokenInterface};

use crate::constants::*;
use crate::errors::TmbError;
use crate::events::Rescued;
use crate::logic::bps_of;
use crate::state::*;
use crate::utils::{core_mint, vault_seeds};

/// Rescues a burned Bro. `fee` comes out of the rescuer's Bro balance; `rescue_burn_bps` of it is
/// SPL-burned from the vault, the rest is credited to the revived Bro, which is re-minted (a burned
/// Core asset can't be un-burned) to the original last owner with the original name/uri.
pub fn handler(ctx: Context<Rescue>, fee: u64) -> Result<()> {
    let a = ctx.accounts;
    require!(!a.config.paused, TmbError::Paused);
    require!(
        fee > 0 && a.config.rescue_fee_options.contains(&fee),
        TmbError::InvalidRescueFee
    );
    require_keys_neq!(
        a.rescuer.key(),
        a.graveyard.last_owner,
        TmbError::SelfRescue
    );
    {
        let r = &a.rescuer_bro;
        require!(r.status == BroStatus::Active, TmbError::BroBurned);
        require!(r.in_escrow, TmbError::NotInEscrow);
        require!(r.pending_spin.is_none(), TmbError::SpinPending);
        require!(r.tmb_balance >= fee, TmbError::NotEnoughBags);
    }
    let burn_amount = bps_of(fee, a.config.rescue_burn_bps).ok_or(TmbError::Overflow)?;
    let credit = fee.checked_sub(burn_amount).ok_or(TmbError::Overflow)?;
    require!(
        a.config.collection != Pubkey::default(),
        TmbError::CollectionNotSet
    );

    // --- state first ---
    a.rescuer_bro.tmb_balance -= fee;
    // fee leaves the rescuer's balance; only the credited part stays as user balance, burn leaves the vault
    a.config.total_user_tmb = a
        .config
        .total_user_tmb
        .checked_sub(burn_amount)
        .ok_or(TmbError::Overflow)?;
    let nb = &mut a.new_bro_record;
    nb.asset = a.new_asset.key();
    nb.owner = a.graveyard.last_owner;
    nb.loss_streak = 0;
    nb.tmb_balance = credit;
    nb.holdings = Vec::new();
    nb.status = BroStatus::Active;
    nb.in_escrow = false;
    nb.pending_spin = None;
    nb.total_spins = 0;
    nb.eligible_slot = 0;
    nb.bump = ctx.bumps.new_bro_record;

    // --- burn the burn share of the fee out of the vault ---
    if burn_amount > 0 {
        let bump = a.config.vault_bump;
        let seeds = vault_seeds(&bump);
        token_interface::burn(
            CpiContext::new_with_signer(
                a.token_program.to_account_info(),
                Burn {
                    mint: a.tmb_mint.to_account_info(),
                    from: a.vault_tmb.to_account_info(),
                    authority: a.vault.to_account_info(),
                },
                &[&seeds],
            ),
            burn_amount,
        )?;
    }

    // --- re-mint the fallen Bro to its last owner ---
    core_mint(
        &a.mpl_core_program.to_account_info(),
        &a.new_asset.to_account_info(),
        &a.collection.to_account_info(),
        &a.config.to_account_info(),
        a.config.bump,
        &a.rescuer.to_account_info(),
        &a.last_owner.to_account_info(),
        &a.system_program.to_account_info(),
        a.graveyard.name.clone(),
        a.graveyard.metadata_uri.clone(),
    )?;

    emit!(Rescued {
        burned_asset: a.graveyard.asset,
        new_asset: a.new_asset.key(),
        rescuer: a.rescuer.key(),
        rescuer_asset: a.rescuer_bro.asset,
        last_owner: a.graveyard.last_owner,
        fee,
        burned_amount: burn_amount,
        credited: credit,
    });
    Ok(())
}

#[derive(Accounts)]
pub struct Rescue<'info> {
    #[account(mut)]
    pub rescuer: Signer<'info>,
    #[account(mut, seeds = [CONFIG_SEED], bump = config.bump)]
    pub config: Box<Account<'info, Config>>,
    /// CHECK: only its key is used, to bind the rescuer's BroRecord PDA.
    pub rescuer_asset: UncheckedAccount<'info>,
    #[account(
        mut, seeds = [BRO_SEED, rescuer_asset.key().as_ref(), rescuer.key().as_ref()],
        bump = rescuer_bro.bump
    )]
    pub rescuer_bro: Box<Account<'info, BroRecord>>,
    /// Closed on rescue; rent goes to the rescuer.
    #[account(
        mut, close = rescuer,
        seeds = [GRAVEYARD_SEED, graveyard.asset.as_ref()], bump = graveyard.bump
    )]
    pub graveyard: Box<Account<'info, Graveyard>>,
    /// New Core asset keypair, generated by the client.
    #[account(mut)]
    pub new_asset: Signer<'info>,
    /// CHECK: equals graveyard.last_owner; becomes the owner of the re-minted asset.
    #[account(address = graveyard.last_owner)]
    pub last_owner: UncheckedAccount<'info>,
    #[account(
        init, payer = rescuer, space = 8 + BroRecord::INIT_SPACE,
        seeds = [BRO_SEED, new_asset.key().as_ref(), last_owner.key().as_ref()], bump
    )]
    pub new_bro_record: Box<Account<'info, BroRecord>>,
    /// CHECK: must be the configured Bro collection.
    #[account(mut, address = config.collection @ TmbError::CollectionNotSet)]
    pub collection: UncheckedAccount<'info>,
    /// CHECK: PDA owning the vault token accounts.
    #[account(seeds = [VAULT_SEED], bump = config.vault_bump)]
    pub vault: UncheckedAccount<'info>,
    #[account(mut, address = config.tmb_mint)]
    pub tmb_mint: InterfaceAccount<'info, Mint>,
    #[account(
        mut,
        associated_token::mint = tmb_mint,
        associated_token::authority = vault,
        associated_token::token_program = token_program
    )]
    pub vault_tmb: InterfaceAccount<'info, TokenAccount>,
    pub token_program: Interface<'info, TokenInterface>,
    /// CHECK: pinned to the Metaplex Core program.
    #[account(address = mpl_core::ID)]
    pub mpl_core_program: UncheckedAccount<'info>,
    pub system_program: Program<'info, System>,
}
